### PR TITLE
Updated for latest Laravel structure

### PR DESCRIPTION
**Pull request by ikari7789**
Replaces #11.

Added ability to add Laravel "linked_dirs." (optional)
Made permissions settings optional.
Added task for seeding database.
Added task for uploading dotenv file.
Added logic to create folders for ACL if they don't exist.
Added logic to determined shared folders and operations based on Laravel framework version.
Updated README.md
Migrations use different settings than default artisan commands in case you have special database requirements.
Migrations also use different roles since you don't need to run migrations from all servers, only one.

### CODE REVIEW

**Comment by peterjmit** [comment]
Hi @ikari7789 sorry for the lengthy wait on this. As I am not a of Laravel, perhaps you would be interested in taking over this repo?

Thanks!

Pete

**Comment by ikari7789** [comment]
@peterjmit thanks for the reply! Sure, I can take over the management.

**Comment by peterjmit** [comment]
@ikari7789 you are now a collaborator on this repo, and I've added your email address listed on github to the gem owner list

**Comment by ikari7789** [comment]
@peterjmit Cool, sounds great. I'll make sure what I have on here is up-to-date with what my team has currently been using in production, merge in these edits on Monday, and take it from there. Should make some people happy.

**Comment by HogeBlekker** [comment]
@ikari7789 Makes me happy at least! Thanks.

**Comment by HogeBlekker** [comment]
@ikari7789 I've written a task which symlinks an evironment file (e.g. env/production) to .env instead of uploading it from your development environment. Should I turn it into a pull request?

**Comment by ikari7789** [comment]
Yes please. I've been considering re-examining that step. I wrote my current PR about 2 days after learning what Capistrano was. Not a ruby developer myself, so any edits are welcome.

**Comment by ikari7789** [comment]
Merged and updated to 0.0.3. Gem is released.
Will continue improving from here. Certainly could use some tests.

**Pull request merged**
