### PR TITLE
Feature/add laravel version support

### PR DESCRIPTION
**Pull request by ikari7789**
Major rewrite of this plugin to allow for more tasks and differences depending on Laravel version.

### CODE REVIEW

**Comment by nwp** [comment]
Is there any plan to merge this? It looks like a nice contribution.

**Comment by philbates35** [comment]
+1 This would be very useful.

**Comment by Arcrammer** [comment]
Does this add support for Laravel 5+?

**Comment by ikari7789** [comment]
Yes

**Comment by llbbl** [comment]
+1

**Pull request closed without merging**
